name: arte
version: '${version}'
main: the.grid.smp.arte.Arte
api-version: '1.20'
commands:
  arte:
    usage: /arte reload
depend:
  - communis
libraries:
  - commons-codec:commons-codec:1.16.0
  - org.apache.commons:commons-compress:1.21