port: 1864
address: 0.0.0.0

mode: BASIC
prompt: 'Hello! Please download the resource pack!'

use-cache: true
scramble: true

# optionals. if whitelist is true, then the list represents optional packs
namespaces: []
whitelist: true

groups: []