port: 1864
address: 0.0.0.0

mode: BASIC
scramble: true
prompt: 'Hello! Please download the resourcepack!'

# optionals. if whitelist is true, then the list represents optional packs
namespaces: []
whitelist: true

groups: []