name: arte
version: '${version}'
main: the.grid.smp.arte.bukkit.ArtePlugin
api-version: '1.20'
commands:
  arte:
    usage: /arte <reload|clear>
    permission: arte.command
permissions:
  arte.command:
    default: op
depend:
  - communis
libraries:
  - commons-codec:commons-codec:1.16.0
  - org.apache.commons:commons-compress:1.25.0