name: arte
version: '${version}'
main: io.shardmc.arte.bukkit.ArtePlugin
api-version: '1.20'
softdepend: [ ProtocolLib ]
authors:
  - DrTheo_
  - NikSne
commands:
  arte:
    usage: /arte <reload|clear>
    permission: arte.command
permissions:
  arte.command:
    default: op
libraries:
  - commons-codec:commons-codec:1.16.0
  - org.apache.commons:commons-compress:1.21
folia-supported: true