name: Auto-Release

on:
  push:
    tags: [v*.*]

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'bukkit/build/libs/*.jar,fabric/build/libs/*.jar,fabric-1.20.3/build/libs/*.jar'
